FROM python:3.7.3-alpine3.9

RUN apk add --no-cache \
	bash \
	gcc \
	make \
	musl-dev

COPY requirements.dev.txt /requirements.dev.txt
RUN pip3 install --no-cache-dir -r /requirements.dev.txt

WORKDIR /code

ENTRYPOINT ["/bin/bash", "-c"]
